### ISSUE TITLE
composer.lock should not be git.ignore-d but needs to be checked in

### ISSUE THREAD

**Issue by milovanderlinden** [City-of-Bloomington/blossom#15]
http://stackoverflow.com/questions/12896780/should-composer-lock-be-committed-to-version-control

**Comment by inghamn** [comment]
I'm still learning composer stuff, and can probably be convinced.

Here's what I've been working with:
Lately, in Blossom, I've been fighting composer as I've been working on the various 4 branches.

It has worked well to specify the branch in composer.json, but I still want to pull in updates on that branch over time.

I guess I've been doing it wrong?  As long as the libraries use semantic versioning, we can pull down library updates (in production) using composer.   As I type that, I see how wierd that sounds, but we have zero unit tests.  For our Blossom-lib libraries, I really am looking for a way to propogate updates across all our applications that use them.

For the zend and aura libraries, I am thinking it's a good thing to be able to pull down all the latest fixes for a specific branch version.
